name: customer_milkman
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  intl: ^0.18.0
  sizer: ^2.0.15
  connectivity_plus: ^5.0.2
  table_calendar: ^3.0.0
  get: ^4.6.6
  flutter_calendar_carousel: ^2.2.1


  flutter_rating_bar: ^4.0.1





  responsive_size_utils: ^0.1.6

  shared_preferences: ^2.2.2
  otp_text_field: ^1.1.3
  logging: ^1.2.0
  json_annotation: ^4.4.0
  flex_color_scheme: ^7.3.1
  ionicons: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1




flutter:


  uses-material-design: true


  assets:
    - images/company_logos/
    - images/bg.jpg
    - images/avatar.png





  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
